version: '3'

services:
  user:
    restart: always
    image: amalthundiyil/cm-user:latest
    build:
      context: './src/user'
    container_name: cm-user
    command: sh -c "uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8001:80"
    volumes:
      - .:/usr/app/src
  gateway:
    restart: always
    image: amalthundiyil/cm-gateway:latest
    build:
      context: './src/gateway'
    container_name: cm-gateway
    command: sh -c "uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80"
    environment:
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      USERS_SERVICE_URL: ${USERS_SERVICE_URL}
    ports:
      - "8002:80"
    volumes:
      - .:/usr/app/src
volumes:
  data:
