version: '3'

services:
  mongo:
    image: mongo
    container_name: cm-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    container_name: cm-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  ingester:
    restart: always
    image: amalthundiyil/cm-ingester:latest
    build:
      context: './src/ingester'
    container_name: cm-ingester
    command: sh -c "uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80"
    environment:
      MAPS_API_KEY: ${MAPS_API_KEY}
    ports:
      - "8000:80"
    volumes:
      - .:/usr/app/src
  user:
    restart: always
    image: amalthundiyil/cm-user:latest
    build:
      context: './src/user'
    container_name: cm-user
    command: sh -c "uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8001:80"
    volumes:
      - .:/usr/app/src
  gateway:
    restart: always
    image: amalthundiyil/cm-gateway:latest
    build:
      context: './src/gateway'
    container_name: cm-gateway
    command: sh -c "uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80"
    environment:
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      USERS_SERVICE_URL: ${USERS_SERVICE_URL}
    ports:
      - "8002:80"
    volumes:
      - .:/usr/app/src

volumes:
  data:
